pascalabcnet/pascalabcnet

- pabcnetc/ConsoleCompiler.cs
It will disable all `Console.Buffer*` and `Console.Cursor*` calls. Useful for some environments such as psexec or Appveyor that have output redirection enabled.
So, that's a big step towards running the automated tests on Appveyor.
Closes #118.
> ConsoleCompiler: add /noconsole switch

- Compiler/Compiler.cs
При использовании NuGet-пакетов, подключаемых через директиву компилятора `$reference`, очень часто возникают ошибки загрузки транзитивных сборок, которые совершенно невозможно отладить без логирования в указанных местах.
Например, если я пытаюсь сделать `{$reference ./packages/System.Reactive.Core/lib/net45/System.Reactive.Core.dll}`, при компиляции вылетает ошибка:
```
[0][1,3] Program.pas: Error by reading assembly './packages/System.Reactive.Core/lib/net45/System.Reactive.Core.dll'
````
Из такой ошибки непонятно, что происходит на самом деле. После патча эта ошибка аннотируется следующими сообщениями:
```
System.Reflection.ReflectionTypeLoadException: Не удается загрузить один или более запрошенных типов. Обратитесь к свойству LoaderExceptions для получения дополнительных сведений.
Не …
```
> Compiler: log reflection type load exceptions

- pabcnetc_clear/ConsoleCompiler.cs
Здравствуйте!
Во-первых,  хочу выразить свое уважение за этот проект. Даже в свои школьные годы я прочувствовал разницу между PascalABCNet и каким-нибудь Free Pascal.
Сейчас я разрабатываю местную систему тестирования, на которой проводятся серьезные региональные олимпиады. 
В ней мы используем голый pabcnetcclear.  Почти у всех используемых нами компиляторов  есть опция, позволяющая задать имя екзешника, который получается в результате компиляции. Для упрощения нашей жизни, хотелось бы чтобы и pabcnetcclear такая опция присутствовала.
Собственно, в этом пулреквесте она и реализована
> pabcnetcclear output executable name

- bin/Highlighting/PascalABCNET.xshd
Было:
Стало:
Нормально подсвечиваются и операторы:
Единственный минус в том, что цифры внутри фигурных скобочек будут черными, потому что нет возможности указать цвет цифр внутри RuleSet'а. Но это небольшая потеря, учитывая насколько интерполированные строки теперь читабельнее.
> Адекватная подсветка форматных строк

- TestSuite/partial_constructor3.pas
- TestSuite/partial_constructor4.pas
- TestSuite/partial_constructor5.pas
- TestSuite/partial_constructor6.pas
- TreeConverter/TreeConversion/syntax_tree_visitor.cs
- TreeConverter/TreeRealization/Collections.cs
Добавил кучу тестов, чтоб уже наверняка исправить всё.
По алгоритму - вместо того чтоб подменять предыдущий дефолтный конструктор, я сделал так, чтоб новый в принципе не генерировался (но только если предыдущий уже существует).
При этом вместо подмены всего тела конструктора - подменяется только первый оператор. И только если это неявный вызов конструктора предка.
Правда с одним исключением:
```
type
t1 = partial class
constructor;
begin
inherited Create;
end;
end;
t0 = class
constructor := Writeln('Конструктор предка');
end;
t1 = partial class(t0)
end;
begin
new t1;
end.
```
`inherited Create;` тут вызван явно, но при чтении первого тела `t1` - это вызов конструктора `object`, что плохо. Его тоже заменяет на вызов конструктора `t0`.
> Исправление #2440

- _RebuildReleaseAndRunTests.sh
sh -e will cause the shell to exit immediately if a command exits with a
nonzero exit value.
> Exit build shell script on first subcommand failed

- pabcnetc/ConsoleCompiler.cs
Console program should not override background color to predefined color
because users can use terminal color scheme black on white for example.
Function WriteColorText() is rewrited to display text in specified
foreground color without change background color to fix #211.
> Do not change background color of console output

- README.md
I just spotted a little mistake in the English section of Readme. It was saying "или" instead of "or".
> Replace a Russian word in the English section

- Compiler/Compiler.cs
- pabcnetc_clear/ConsoleCompiler.cs
Тот же `{$define}`, но работает из вне .pas файла.
Нужно, чтоб автоматически генерировать особую версию .exe из существующих .pas файлов.
К примеру, версию с дополнительными фичами дебага, для особых проверок во время работы тестировщика проекта.
> Агрумент консольного компилятора /Define

- VisualPascalABCNET/FileMonitoring.cs
```
{$reference System.Windows.Forms.dll}
{$reference System.Drawing.dll}
{$apptype windows}
uses System.Windows.Forms;
uses System.Drawing;
begin
var MainForm := new Form;
MainForm.Activated += (o,e)->
begin
MessageBox.Show(nil);
end;
Application.Run(MainForm);
end.
```
Попробуйте закрыть окно нажав на крестик.
Это невозможно, потому что окно программы прячется за окна других программ при закрытии месседжбокса.
https://youtu.be/hmICbhDRyhQ
---
Так вот - примерно то же самое сейчас делает IDE паскаля.
Я тупо засунул код, создающий месседжбоксы, в `Task.Run`.
И только в одном месте - там где это достало меня, потому что я часто работаю с кодогенераторами в POCGL, то есть с ситуациями где одна программа меняет текст другой.
Этот пулл это **только пример исправлений**, лучше если вы …
> Месседжбокс "Файл был изменён" в отдельный поток

- pabcnetc_clear/ConsoleCompiler.cs
Решил разобраться с тем, почему у меня в тестах ошибок POCGL где-то ошибки на русском, где-то на англ., а где то всё в перемешку.
В итоге в очередной раз разобрался, что в инициализации `PABCSystem` выполняется:
```
System.Threading.Thread.CurrentThread.CurrentUICulture := System.Globalization.CultureInfo.GetCultureInfo(locale_str);
```
`locale_str` всегда будет русской, если компилятор явно не указал иначе. А (без этого пула) другие значения возможны только при компиляции из IDE.
- Эту штуку так просто из инициализации программы не вычленишь.
- Перезапись `CurrentUICulture` между тем что делает `PABCSystem` и запуском кода программы вставить рефлекцией не выйдет. Возможно можно инъекциями кода, но это слишком.
- В начале каждой программы теста вставлять эту строчку тоже глупо - это …
> Аргумент консольного компилятора "/Locale"

- TreeConverter/NetWrappers/NetHelper.cs
Closes #2718.
I'm not sure my fix is correct, but it unblocks a huge chunk of work on PascalABC.NET SDK (since various wild reference assemblies containing type `T` no longer can cause a compilation error, provided that the types in question are unused by my Pascal programs).
> (#2718) NetHelper: fix type lookup when it has several entries

- NETGenerator/NETGenerator.cs
- SemanticTree/SemanticTree.cs
- TestSuite/generics66.pas
- TestSuite/recursive_where_gen.pas
- TreeConverter/TreeConversion/syntax_tree_visitor.cs
- TreeConverter/TreeRealization/generics.cs
- TreeConverter/TreeRealization/types.cs
https://github.com/SunSerega/pascalabcnet/actions/runs/3198665661
- Тест `recursive_where_gen.pas` это дубль теста `recursive_where.pas` из #2727, но все дочереные типы сделаны шаблонными.
После того пула так всё ещё не работало, потому что для них `foreach (generic_type_instance_info gti ...` надо делать перед проверками `where`.
- Тест `generics66.pas` частично работал до первого коммита этого пула: `t1<T>` компилировался, а `t2<T>` нет.
После первого коммита и `t1<T>` перестал компилироваться, а второй коммит исправил оба случая.
> Чистка за #2727 и исправление заранее созданных подстановок в шаблон типа

- Compiler/Compiler.cs
Только сейчас заметил, `File.Exists` применяется перед присвоением `cdo.MainResourceFileName` - в итоге для всех `$mainresource` пишет будто файл ресурса не найден.
> Чистка за #2819

- Compiler/Compiler.cs
Припоминаю, когда делал изначальный рекурсивный `uses-in` - взял `CurrentCompilationUnit.SyntaxTree.file_name` из предыдущей реализации не задумываясь.
Теперь заменил на файл контекста синтаксической ноды `uses` - поэтому такое же проблемы быть не может:
Так же добавил в #2656, потому что он меняет тот же кусок кода.
В общем случае так делать конечно не хорошо, но тут изменение тривиальное, бороться с конфликтами иначе будет больше лишнего труда.
Проще говоря, если примете тот пулл - этот не нужен.
https://github.com/SunSerega/pascalabcnet/actions/runs/4714641880
> Правильное имя файла в ошибках `uses`

- ReleaseGenerators/PascalABCNETConsoleZIP.bat
Сейчас при попытке что-либо компилировать с помощью `pabcnetcclear.exe` - я получаю следующую ошибку:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'LambdaAnySynToSemConverter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
at PascalABCCompiler.SyntaxTreeConverters.SyntaxTreeConvertersController.AddStandardConverters()
at PascalABCCompiler.SyntaxTreeConverters.SyntaxTreeConvertersController.AddConverters()
at PascalABCCompiler.Compiler.Reload()
at PascalABCCompiler.ConsoleCompiler.Main(String[] args)
```
Похоже, вы забыли добавить этот файл в zip релиз...
P.S. Пересобрал - теперь компиляция работает.
> Добавление `LambdaAnySynToSemConverter.dll` to zip релиз

- pabcnetc_clear/ConsoleCompiler.cs
Сейчас если параметром `/SearchDir` передать неправильный (не существующий или невалидный) путь - его игнорирует, вместо того чтобы явно об этом дать ошибку.
> Ошибка для неправильных путей "/SearchDir"

- Optimizer/Optimizer.cs
Контекст: https://github.com/pascalabcnet/pascalabcnetide/issues/250
При исправлении той issue @ibond84 добавил код:
```
if (vdn.type is generic_instance_type_node)
tuples_num = (vdn.type as generic_instance_type_node).generic_params.Count;
else if (vdn.type is compiled_type_node)
tuples_num = (vdn.type as compiled_type_node).compiled_type.GetGenericArguments().Length;
```
Но в каком то случае у меня кидало `NullReferenceException`.
В студии дебагом я понял что проблема в том, что `.generic_params` было `null`.
`.generic_params`, вообще, выглядело неправильно: Тут проверяется сколько типов которые подставили в `vdn.type.original_generic`, а не сколько типов можно подставить в `vdn.type`.
Ну, я отложил этот вопрос, чтобы сначала найти источник более неприятного краша (#2892) - и теперь не …
> Исправление... Чего то?

- .github/workflows/buildandruntests.yml
@ibond84 последнее время выполняет тесты перед тем как закрыть issue:
> ![image](https://github.com/pascalabcnet/pascalabcnet/assets/27270190/4274d93e-7eae-4fd2-95ba-e7755c63b0a5)
И просит так же делать в пулл-реквестах.
Я недавно разбирался с GitHub Actions - там для этого есть уже готовый функционал, чтобы каждый раз вручную это не делать.
---
Слева от каждого коммита будет символ, показывающий его состояние, к примеру:
- Для ещё тестируемого коммита:
>![image](https://github.com/pascalabcnet/pascalabcnet/assets/27270190/ffd1d2eb-cec2-480a-882e-e5bca270b115)
- Для проваленного тестирования (в данном случае он был отменён а не провален, я специальной запостил +1 коммит, чтобы этот коммит стал устаревшим):
> ![image](https://github.com/pascalabcnet/pascalabcnet/assets/27270190/9340fe0e-fac …
> Автоматизация выполнения тестов

- TreeConverter/NetWrappers/NetHelper.cs
In #2905, we still have a resource leak even after this patch.
As a mid-term solution, I am planning to add a static cache for resolved assemblies.
As a long-term solution, I'll try to find a proper _scope_ for the assemblies used during a particular compilation, and maybe even try to unload them after a compilation request has been processed.
This way, our compiler process will become reusable for different projects and won't have the leaked assemblies in it indefinitely.
> (#2905) Short-term solution: load Microsoft assemblies via Assembly::LoadFrom

- Compiler/PCU/PCUReader.cs
В `PCUReader.FindSpecTypeByHandle()` имена типов переводятся в `PCUReader.TypeSpec`
Обычно заполняется поле `TypeSpec.t`, но если `System.Type` получить не удалось, то заполняется `TypeSpec.name`
`SystemType` для `System.Windows.UIElement` получить как раз не удалось (`NetHelper.FindTypeOrCreate(type_name)` возвращает `null`). Поэтому заполнилось поле `name` как "**System.Windows**.UIElement"
Дальше экземпляр `TypeSpec` уходит в `PCUReader.ChooseConstructor()` где поле `name` сравнивается с `System.Type.Name`, которое всегда возвращает имя типа без неймспейса. `TypeSpec.name` был заполнен с неймспейсом
В `.FindSpecTypeByHandle()` уже применялась практика обрезки неймспейса чуть ниже по коду, так что я просто добавил её и сюда
<details>
<summary>Спойлер: Лирическое отступление</summary> …
> Исправление #2901

- Compiler/Compiler.cs
- TreeConverter/NetWrappers/AssemblyResolveScope.cs
- TreeConverter/NetWrappers/NetHelper.cs
- VisualPascalABCNET/Workbench/ProjectService.cs
Этот pull request исправляет утечку ресурсов, которую мы обнаружили в #2905 (и которая была ранее добавлена моим же предыдущим pull request'ом).
Поскольку у нас теперь единый `AssemblyResolveScope` на все процессы перекомпиляции (я не придумал, как можно сделать что-то лучше решения от @ibond84), то я решил настроить кэширование в этом контексте.
Воркэраунд для сборок от Microsoft стал не нужен — теперь все сборки одинаково правильно грузятся общим кодом (во всяком случае, пример с Microsoft.ML теперь компилируется хорошо).
Отдельный метод `NetHelper.PreloadAssembly` тоже перестал быть нужен.
> (#2905) More design fixes for AssemblyResolveScope, fix leaks

- Compiler/Compiler.cs
- NETGenerator/AppConfigUtil.cs
- NETGenerator/CodeGenerator.cs
- NETGenerator/NETGenerator.cs
- NETGenerator/NETGenerator.csproj
- TreeConverter/NetWrappers/AssemblyResolveScope.cs
Теперь [пример с ML из замечаний к версии 3.9.0](https://pascalabcnet.github.io/mydoc_release_notes_3_9_0.html) компилируется и запускается без дополнительных действий. Для него генерируется такой конфигурационный файл:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<runtime>
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
<dependentAssembly>
<assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
<bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.2.0.1" />
</dependentAssembly>
</assemblyBinding>
</runtime>
</configuration>
```
Это также соответствует поведению C# SDK, если ей на вход подать такой же набор NuGet-пакетов.
В процессе тестирования этой функции обнаружил интересный аспект поведения: …
> Generate application configuration files on compilation

- TestSuite/IntRange comb.pas
- bin/Lib/PABCSystem.pas
Изначально было
```
for var i := 0 to self.Count-1 do
```
Я оттестировал, но затем сделал чтобы массив результата не переполнялся:
```
for var i := 0 to System.Math.Min(self.Count, a.Length-arrayIndex) do
```
И в итоге потерял `-1`...
> Исправление бага на пересечении `IntRange` и комбинаторики

- Compiler/Compiler.cs
Важно очищать ошибки, связанные с PABCRtl.dll до вызова события о конце компиляции, иначе они будут выводиться в сообщениях компилятора.
> Fix clearing errors when using PABCRtl.dll

- ParserTools/ParsersController.cs
По сути это там изначально должно было бы:
Если `.GetTypes()` кидает `ReflectionTypeLoadException` - вместо внятного текста ошибки оно говорит используйте свойство `.LoaderExceptions`.
Вот в этом пуле я сделал чтобы это свойство использовало.
> Более подробная ошибка в консольном компиляторе при загрузке сборок

- Compiler/Compiler.cs
- TestSuite/usesunits/UsesInUnits6/A.pas
- TestSuite/usesunits/UsesInUnits6/B.pas
- TestSuite/usesunits/UsesInUnits6/C.pas
- TestSuite/usesunits/uses_in6_cycle_with_implementation_dependency.pas
Исправлен случай ложного возникновения ошибки циклической зависимости интерфейсов. В соответствующей ошибке проверке не была учтена возможность цикла с присутствующими в нем связями из implementation части.
> Fix interfaces loop dependency check

- LanguageIntegrator/LanguageIntegrator.cs
Чтобы не было ошибок в консольном компиляторе и версии для линукса добавлена проверка на наличие папки LanguageKits.
> Add check for LanguageKits directory existence

- TestSuite/ObjectToString.pas
- TestSuite/ObjectToString.txt
- TestSuite/tttn1.pas
- bin/Lib/PABCSystem.pas
```
```
Сейчас это выводит `integer`.
`Type.GetTypeCode` работает по-особому с энумами:
https://learn.microsoft.com/en-us/dotnet/api/system.type.gettypecode?view=net-8.0#remarks
Поэтому его надо отдельно обрабатывать, чтобы энумы правильно выводило.
> Исправление `TypeToTypeName` для энумов

- NETGenerator/NETGenegratorTools.cs
- NETGenerator/NETGenerator.cs
`ldnull` лучше чем `ldc0` когда речь идёт об указателях и `IntPtr`, но mono об этом не знает.
Данный пулл исправляет проблему из этой темы на форуме:
https://forum.mmcs.sfedu.ru/t/kak-rabotat-so-svyazannymi-spiskami-zapisyami-pod-linux/4225/13
Обходя эту issue mono:
https://github.com/mono/mono/issues/20709
Путём замены всех `OpCodes.Ldnull` на `OpCodes.Ldc_I4_0` в компиляторе.
> Замена `Ldnull` на `Ldc_I4_0`

- Parsers/PascalABCParserNewSaushkin/ABCPascalParserTools.cs
Исправлена ошибка NullReferenceException в ParseDirective для директивы без параметров.
> Fix directives format null bug

- Compiler/Compiler.cs
fix #3116
Там наложилось 2 проблемы:
1. Функция `FindPCUFileName` могла найти `.pas` файлы - если указать расширение (.pas) файла в `uses-in`
2. `CompilerOptions.OutputDirectory` использовалось даже если оно не было установлено (опция "Генерировать выходные файлы в папку" в редакторе. по-умолчанию папка Output). В таком случае .pcu брало из папки с основным .pas файлом программы.
> Исправление #3116

- bin/Lib/PABCSystem.pas
https://t.me/c/1773182219/4249
Тут указали на полные список юникодных символов:
https://en.m.wikipedia.org/wiki/Newline#Unicode
А в текущей реализации `.ToLines` - оно вообще не может обработать текстовые файлы созданные на одной ОС, но прочитанные на другой.
Существующие в стадартных библиотеках .Net методы ведут себя так:
```
while true do
begin
var l := r.ReadLine;
if l=nil then break;
$'[{l}] = {ObjectToString(l.Select(ch->''$''+ch.Code.ToString(''X'')))}'.Println;
end;
```
```
[a] = [$61]
[b] = [$62]
[c] = [$63]
[d
efg
h
i] = [$64,$B,$65,$C,$66,$85,$67,$2028,$68,$2029,$69]
```
И в Net8.0 Так же:
```
var r = new StringReader("a\r\nb\nc\rd\ve\ff\u0085g\u2028h\u2029i");
while (true)
{
var l = r.ReadLine();
if (l == null) break;
Console.WriteLine($"[{l}] = [{string.Join(',', …
```
> Синхронилировал поведение `.ToLines` со стандартными типами .Net, как `System.IO.StringReader`

- Compiler/Compiler.cs
`OutputDirectory` не всегда полный путь. К примеру если вызвать `pabcnetcclear .\a.pas`, `OutputDirectory` оказывается `.\`
Я не нашёл чтобы от этого ещё что то ломалось, только .dll в этой же папке лишний раз копирует поверх самой себя. С этим пулом больше не копирует.
> Исправление копирования .dll в `GetReferenceFileName`

- .github/workflows/build_separate_proj.yml
- Compiler/Compiler.csproj
- VisualPascalABCNET/VisualPascalABCNET.csproj
- VisualPascalABCNET/VisualPascalABCNET_40.csproj
- VisualPascalABCNETLinux/VisualPascalABCNETLinux.csproj
Компилятор использует `PascalLanguage` и `PascalABCParserNewSaushkin` как языковой плагин, то есть .dll-ки этих 2 проектов подгружаются из компилятора.
И компилятор ожидает что их содержимое будет соответствовать версии исходников, к примеру после прыжка между ветками, или даже просто после выполнения `git pull`.
Но в то же время эти 2 проекта подгружаются как плагины, их типы не должны быть напрямую видны из компилятора.
Поэтому я добавил их в зависимости, но с
```
<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
```
Таким образом их пересобирает вместе с компилятором, если что то поменялось (или если они небыли созданы ещё)
---
Так же, первым коммитом добавил новый workflow, проверяющий что все проекты можно собрать отдельно.
Для проекта `PABCNETCclear` там особая проверка, …
> Исправление зависимостей проектов

- bin/Lib/PABCSystem.pas
`t.FullName` может быть `nil`:
```
Print( typeof(System.Nullable<>).GetGenericArguments.Single.FullName );
```
Поэтому новый код для `NewSet<>` у меня падал при сборке POCGL.
Исправление протестил - теперь всё собирается.
> Исправление NRE в `TypeName`

- CodeCompletion/CodeCompletion.cs
- CodeCompletion/TypeTable.cs
- VisualPascalABCNET/IB/CodeCompletion/CodeCompletionParserController.cs
- VisualPascalABCNETLinux/IB/CodeCompletion/CodeCompletionParserController.cs
Добавлена очистка кэша типов и методов расширения у стандартных типов, чтобы избежать сохранения ссылок на неактуальные InterfaceUnitScope и ImplementationUnitScope во время перекомпиляции анализатором кода модуля PABCSystem. Тесты показывают, что теперь сборщик мусора очищает память после срабатывания Intellisense. Однако, все еще не решена проблема дубликатов экземпляров шаблонных типов, поэтому может быть временный рост по памяти вплоть до 500 Мб.
> Intellisense memory leaks fix

- _GenerateLinuxVersion.bat
Случайно было обнаружено, что библиотека используется в `VisualPascalABCNETLinux`, но не копируется в архив
Разумеется в идеале необходимо копировать всю папку, а не отдельные куски, чтобы такие проблемы не возникали регулярно
Однако, чтобы привести репозиторий к такому поведению требуется больше времени
> Копирование SharpDisasm.dll в архив для Linux

- _GenerateAllSetups.bat
По словам @miks1965 строчки были связаны со сборкой для netfx 4.0. Тк сейчас под эту версию сборка не проводится, то строчки потеряли смысл
> Удаление неиспользуемых строчек из `_GenerateAllSetups.bat`

- VisualPascalABCNET/DS/CodeCompletionVisual/TipPainterTools.cs
- VisualPascalABCNETLinux/DS/CodeCompletionVisual/TipPainterTools.cs
Здесь правки, чтобы учитывались скобки внутри параметров метода при парсинге, а также случай, когда разделитель параметров это запятая, как в SPython.
Вообще парсить уже сформированный description и разбивать его заново, выделяя параметры не очень хорошо. Нужно будет переписать это когда-нибудь :)
> Исправление TipPainterTools

- PascalABCLanguageInfo/PascalABCLanguage.cs
- TreeConverter/TreeConversion/SemanticRulesConstants.cs
- TreeConverter/TreeConversion/syntax_tree_visitor.cs
- TreeConverter/TreeRealization/type_table.cs
- TreeConverter/TreeRealization/types.cs
В зависимости от константы AllowMethodCallsWithoutParantheses разрешаем преобразование имени метода в вызов метода.
> Исправление вызовов методов без скобочек для языков с отличающихся от PascalABC.NET этим поведением

- NETGenerator/NETGenerator.cs
В `t.Name` содержится имя компилируемого типа, например `IReadOnlyList<PascalType>`
Однако правым операндом сравнения выступает имя наследника `System.Type`, который используется для выражения компилируемого типа
Теперь сравнение происходит корректно. Однако я не нашёл ни одного случая, когда эта ветка вообще выполнялась
> Исправление сравнения имён

- CodeCompletion/CodeCompletion.cs
- CodeCompletion/DomSyntaxTreeVisitor.cs
- CodeCompletion/SymTable.cs
- Compiler/Compiler.cs
- CompilerTools/Tools.cs
- NETGenerator/CodeGenerator.cs
- NETGenerator/NETGenerator.cs
- VisualPascalABCNET/DS/VisualEnvironmentCompiler.cs
- VisualPascalABCNET/DockContent/CodeFileDocumentTextEditorControl.cs
- VisualPascalABCNET/Form1.cs
- VisualPascalABCNET/IB/CodeCompletion/CodeCompletionParserController.cs
- VisualPascalABCNET/IB/CodeCompletion/CodeCompletionProvider.cs
- VisualPascalABCNET/Workbench/BuildService.cs
- VisualPascalABCNET/Workbench/WorkbenchServiceFactory.cs
- VisualPascalABCNETLinux/DS/VisualEnvironmentCompiler.cs
- VisualPascalABCNETLinux/DockContent/CodeFileDocumentTextEditorControl.cs
- VisualPascalABCNETLinux/Form1.cs
- VisualPascalABCNETLinux/IB/CodeCompletion/CodeCompletionParserController.cs
- VisualPascalABCNETLinux/IB/CodeCompletion/CodeCompletionProvider.cs
- VisualPascalABCNETLinux/Workbench/BuildService.cs
- VisualPascalABCNETLinux/Workbench/WorkbenchServiceFactory.cs
- bin/Lib/SPythonSystem.pas
В основном здесь избавление от legacy кода. В частности, в Intellisense закомментирована поддержка случая uses *какой-то тип .NET*, поскольку основной компилятор такой случай не поддерживает.
> Рефакторинг в Intellisense
