ParserTools/ParserTools/DefaultLanguageInformation.cs
```pas
library Liba;
procedure p(a: array[,] of integer) := exit;
procedure pt<T>(a: array[,] of T) := exit;
end.
```
=> Исправление многомерных массивов в метаданных

ParserTools/ParserTools/DefaultLanguageInformation.cs
=> fix pascalabcnet/pascalabcnetide#160

bin/Lib/OpenCL.pas
В #2611 небыло изменений модуля `OpenCL`, поэтому `OpenCLABC` не компилировался...
=> Исправление OpenCLABC

bin/Lib/PABCSystem.pas
На лабе обнаружил, что отсутствует перегрузка ReadBigInteger с приглашением к вводу. Считаю своим долгом это исправить.
=> Добавил ReadBigInteger с приглашением к вводу

SyntaxVisitors/YieldVisitors/ProcessYieldsCapturedVars.cs, TestSuite/yield-where.pas
https://github.com/SunSerega/pascalabcnet/actions/runs/3717564415
=> Исправление #2760

CodeCompletion/CodeCompletion.cs, CodeCompletion/DomSyntaxTreeVisitor.cs, Compiler/Compiler.cs
https://github.com/SunSerega/pascalabcnet/actions/runs/5345034599
=> Разный приоритет .pas и .pcu для всех путей параметра `/SearchDir`

SyntaxVisitors/UniversalVisitors/ABCStatisticsVisitors.cs
=> Исправил подсчёт здоровья - проценты за принт начислялись несколько раз

TestSuite/RangeT count.pas, bin/Lib/PABCSystem.pas
Я уже объяснил свои мысли и альтернативы [тут](https://github.com/pascalabcnet/pascalabcnet/pull/2973#issuecomment-1839377048).
=> `RealRange.Size` 

bin/Lib/PABCSystem.pas
fix #2977
(это надо в описании чтобы связать ту issue)
=> Исправление #2977 - сделал всё в `PABCSystem` совместимым с .Net4.0

Compiler/Compiler.cs
Восстановление директивы TargetFramework после #2984
=> Repair TargetFramework directive

Compiler/PCU/PCUWriter.cs
https://github.com/pascalabcnet/pascalabcnet/commit/02aae1768ba77478454c4d340e096f0785c3617b#r140265425
По этому поводу выпрямил всю логику этой функции
=> Мелкий рефакторинг `AddIndirectUsedUnitsForType`

bin/Lib/PABCSystem.pas
=> Исправление #3088

CodeCompletion/DomSyntaxTreeVisitor.cs
Изменения вырваны из #2656, но #2656 они на самом деле не касаются, поэтому есть смысл разделить.
А ещё есть смысл разделить потому что в этой части постоянные появляются сложно-исправляемые кофликты...
---
По сути я взял кусок кода, который был продублирован 3 раза и вынес его в отдельную подпрограмму.
=> Рефакторинг дублей кода в `DomSyntaxTreeVisitor`

TestSuite/ObjectToString.pas, TestSuite/ObjectToString.txt, bin/Lib/PABCSystem.pas
=> `TypeName`: Вывод картежей

TreeConverter/TreeConversion/syntax_tree_visitor.cs, bin/Lib/ABCObjects.pas, bin/Lib/ABCObjects.xml, bin/Lib/CRT.pas, bin/Lib/CRT.xml, bin/Lib/GraphABC.pas, bin/Lib/GraphABC.xml, bin/Lib/PABCSystem.pas, bin/Lib/PABCSystem.xml
Принято решение удалить файлы XML документации стандартных модулей.
=> Delete xml documentation of standard modules

Localization/Localization.csproj
Теперь сборка языковых ресурсов проводится только при наличии изменений в соответствующих файлах
=> Восстановление возможности кеширования `Localization.dll`

bin/Lib/GraphWPF.pas
если title больше одной строки, показывалась только последняя. теперь все строки будут показаны.
=> высота поля для текста выделяемая под заголовок Title - Update GraphWPF.pas

VisualPascalABCNET/IB/CodeCompletion/CodeCompletionProvider.cs, VisualPascalABCNETLinux/IB/CodeCompletion/CodeCompletionProvider.cs
Исправлена работа shift space, которая случайно нарушилась после рефакторинга в #3213.
=> Fix shift space action in Intellisense

TreeConverter/TreeConversion/syntax_tree_visitor.cs
За одно сделал нейминг в некоторых местах более интуитивным
=> Улучшенная проверка на возможность развернуть `foreach` для Pascal типов

.github/workflows/buildandruntests.yml, _RebuildReleaseAndRunTestsForGitHubActions.bat
This reverts commit da6d44fc334b1dc0caf8975d2f2452cdd88b9702.
=> Revert "Run GitIgnoreTester separately from other tests (#3287)"

bin/Lib/GraphABC.pas
Added new procedure SyncWindow() to update Mono window's content to Linux window
=> Update GraphABC for full support ABCObjects examples

VisualPascalABCNETLinux/DS/Utils/ProcessRunner.cs
fix https://github.com/pascalabcnet/pascalabcnet/issues/3315
=> Update ProcessRunner.cs -- fix for space chars in running app file name

CodeCompletion/DomConverter.cs, CodeCompletion/SymTable.cs
Перестройка описания нужна для правильной работы многоязычности в Intellisense.
=> Добавление обновления описания сущностей из Intellisense перед выводом их в окошке

CodeCompletion/DomConverter.cs, CodeCompletion/SymTable.cs
Проблема с Writeln и Println из предыдущего пулл реквеста поправлена.
=> Обновление описания сущностей в Intellisense

NETGenerator/NETGenerator.cs
В данном куске кода нас интересуют только методы, но выбирались вообще все члены класса, подходящие под условие. Исправил выборку, чтобы избавиться от проверок на тип
=> Небольшой рефакторинг
